[package]
name = "ezlogger"
version = "0.1.0"
edition = "2021"
description = "rust logger based"
license = "MIT"

[dependencies]
log = { version = "0.4", features = ["std"] }
crossterm = "0.26"
time = "0.3"
